server:
  port: 8083

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_losobeatz?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user_losobeatz
    password: 1237
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

    jpa:
      hibernate:
        ddl-auto: update

